/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
static yyconst short int yy_acclist[252] =
    {   0,
       74,   74,   76,   74,   75,    6,   74,   75,    1,    6,
       75,    1,   74,   75,   59,   74,   75,   74,   75,   74,
       75,   65,   74,   75,   58,   74,   75,   74,   75,   11,
       74,   75,   12,   74,   75,   63,   74,   75,   62,   74,
       75,    8,   74,   75,   61,   74,   75,   16,   74,   75,
       64,   74,   75,   74,   75,   74,   75,   15,   74,   75,
        7,   74,   75,   40,   74,   75,   67,   74,   75,   42,
       74,   75,   73,   74,   75,   13,   74,   75,   14,   74,
       75,   47,   74,   75,   73,   74,   75,   73,   74,   75,
       73,   74,   75,   73,   74,   75,   73,   74,   75,   73,

       74,   75,   73,   74,   75,   73,   74,   75,   73,   74,
       75,   73,   74,   75,   73,   74,   75,   73,   74,   75,
       73,   74,   75,    9,   74,   75,   66,   74,   75,   10,
       74,   75,   60,   74,   75,   44,   50,   45,   55,   48,
       35,   51,   36,   52,    4,   49,   71,   14,   13,   37,
       39,   43,   41,   38,   73,   70,   73,   56,   73,   73,
       22,   73,   73,   73,   73,   24,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   57,   46,   68,   72,
        4,   53,   54,   73,   73,   73,   73,   73,   23,   73,
       25,   73,   73,   73,   73,   73,   73,   73,   73,   73,

       73,   69,    5,   73,   17,   73,   73,   19,   73,   73,
       26,   73,   73,   73,   73,   73,   73,   73,   33,   73,
       73,   34,   73,   73,   20,   73,   73,   28,   73,   73,
       73,   73,   73,   21,   73,   18,   73,   27,   73,   29,
       73,   30,   73,   31,   73,   73,   73,   32,   73,    3,
        2
    } ;

static yyconst short int yy_accept[190] =
    {   0,
        1,    2,    3,    4,    6,    9,   12,   15,   18,   20,
       22,   25,   28,   30,   33,   36,   39,   42,   45,   48,
       51,   54,   56,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      137,  137,  137,  137,  137,  137,  138,  139,  140,  140,
      141,  142,  143,  144,  145,  145,  145,  146,  147,  148,
      148,  148,  148,  149,  150,  151,  152,  153,  154,  155,
      156,  157,  158,  158,  159,  160,  161,  163,  164,  165,
      166,  168,  169,  170,  171,  172,  173,  174,  175,  176,

      177,  178,  179,  180,  180,  180,  180,  181,  181,  181,
      181,  182,  183,  184,  185,  186,  187,  188,  189,  191,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      202,  202,  203,  203,  203,  204,  205,  207,  208,  210,
      211,  213,  214,  215,  216,  217,  218,  219,  221,  222,
      222,  222,  224,  225,  227,  228,  230,  231,  232,  233,
      234,  236,  236,  236,  238,  240,  242,  244,  246,  247,
      247,  247,  248,  248,  248,  248,  250,  250,  250,  250,
      250,  250,  251,  252,  252,  252,  252,  252,  252
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   27,   43,
       44,   27,   27,   45,   46,   47,   48,   49,   50,   27,
       27,   51,   52,   53,   54,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    5,    5,
        1,    1,    5,    5,    5,    5,    5,    7,    2,    8,
        8,    9,    5,   10,   11,    2,   12,   13,    9,    5,
       14,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,    1,   15,    9,    5
    } ;

static yyconst short int yy_base[203] =
    {   0,
        0,    0,  320,  756,  756,  756,  756,  290,  304,   51,
      285,   47,    0,  756,  756,  282,   44,  756,   43,   41,
       51,   46,   53,  276,  756,   53,  275,   54,   53,  756,
      756,  239,    0,   54,   59,   61,   66,   73,   85,   65,
       93,   92,   99,  105,   63,  756,  109,  756,  756,  756,
      243,  128,  143,  203,  178,  756,  756,  756,  196,  756,
      756,  756,  756,  756,  133,  152,    0,  756,  756,  139,
      143,  147,  756,  756,  174,  756,  756,  756,  165,  130,
      756,    0,  115,  756,  135,  140,  145,  149,  158,  161,
      164,  170,  173,  175,  179,  189,  185,  195,  198,  204,

      756,  148,  179,  120,  113,  233,  756,  244,  249,  256,
        0,  756,  756,  222,  226,  241,  243,  245,  254,  256,
      259,  265,  269,  278,  283,  287,  289,  298,  300,   85,
       69,  756,  264,  340,  756,  309,  312,  318,  322,  324,
      327,  333,  336,  345,  347,  356,  359,  361,  371,   57,
       47,  365,  377,  375,  380,  386,  395,  392,  397,  406,
      401,   52,   48,  411,  415,  417,  420,  426,  432,  226,
       27,  435,  282,  456,  252,  441,  464,  484,  267,  365,
      490,  756,  756,  508,  516,  523,  545,  756,  598,  179,
      612,  620,  628,  635,  649,  664,  679,  694,  706,  715,

      726,  740
    } ;

static yyconst short int yy_def[203] =
    {   0,
      188,    1,  188,  188,  188,  188,  188,  188,  189,  188,
      188,  188,  190,  188,  188,  188,  188,  188,  188,  188,
      188,  191,  191,  188,  188,  188,  188,  188,  192,  188,
      188,  188,  193,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,   42,  188,  194,  188,  188,  188,
      189,  189,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  195,  196,  197,  188,  188,  188,
      188,  191,  188,  188,  188,  188,  188,  188,  188,   42,
      188,  193,  194,  188,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,

      188,  194,  189,  188,  188,  188,  188,  196,  196,  198,
      197,  188,  188,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,  188,
      188,  188,  196,  196,  188,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,  188,
      188,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,  188,  188,   42,   42,   42,   42,   42,   42,  199,
      188,   42,  199,  199,  200,   42,  188,  188,  200,  200,
      201,  188,  188,  202,  188,  201,  202,    0,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188
    } ;

static yyconst short int yy_nxt[812] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   29,   34,   35,   36,   37,   38,   29,   29,   39,
       29,   40,   29,   29,   41,   42,   29,   43,   44,   45,
       29,   46,   47,   48,   49,   53,   57,   53,   61,   63,
       65,   65,  175,   70,   66,   71,   71,   64,   62,   67,
       70,   58,   72,   72,   74,   68,   75,   76,   78,   79,
       81,   81,  171,   82,   82,   54,   81,  170,   81,   82,
       55,   82,   81,   81,  163,   82,   82,   86,   85,  162,

       81,  100,   80,   82,   87,   83,   83,   88,   93,   80,
      151,   83,   81,   83,   89,   82,   90,   83,   83,   81,
       81,   91,   82,   82,  150,   83,   81,   92,   94,   82,
       95,   96,   81,  101,   52,   82,   81,   83,   97,  188,
      103,   98,   81,  103,   83,   83,  131,   53,   99,   53,
      103,   83,   65,   65,  109,  109,  130,   83,   65,   65,
       70,  102,   71,   71,   70,  110,   72,   72,   80,   80,
      114,  115,  188,   80,   80,   81,   80,   54,   80,   80,
      103,   80,   55,   80,   80,   52,   80,   80,   80,  113,
       59,   80,  116,   59,  117,   80,   80,   80,  112,   80,

       80,  118,   80,   80,   80,  119,  106,   80,   80,   80,
       80,   80,   80,   80,   80,  121,  120,   80,   80,   80,
      105,  122,  123,   80,   80,   80,  124,   80,   80,  126,
      173,   80,  173,   80,   80,   80,   80,  128,  104,  125,
      127,   80,   80,  129,   80,  132,  109,  109,  132,   52,
       80,  109,  109,  136,  132,  132,  179,  110,  134,  134,
       80,   80,  110,   84,   80,   80,  109,  109,   80,  110,
      137,  179,   80,  138,  135,  180,  140,  110,  139,   80,
       80,   80,   80,   80,   80,  132,  173,   80,  173,   80,
      180,   80,   80,   80,   80,   80,  141,   80,   80,   77,

       80,   73,   80,   80,   80,   80,   60,   80,   80,   56,
       52,   80,  142,  143,   50,   80,   80,   80,  145,  188,
      144,   80,   80,  188,   80,   80,   80,   80,  147,   80,
      188,  188,  148,   80,  146,   80,   80,   80,   80,   80,
      188,  149,  109,  109,   80,  188,   80,   80,   80,  152,
       80,   80,  188,  110,  188,   80,   80,   80,   80,  153,
       80,   80,   80,   80,   80,   80,   80,  188,   80,  188,
      154,   80,   80,   80,   80,   80,  188,  155,  188,   80,
      157,  188,  156,   80,   80,   80,   80,  188,  188,  159,
      158,   80,  188,   80,   80,   80,  160,   80,   80,   80,

       80,  188,   80,   80,   80,   80,  161,   80,  188,   80,
       80,   80,  164,   80,   80,   80,   80,   80,   80,   80,
      188,   80,  165,   80,   80,   80,   80,  188,  167,  166,
       80,   80,   80,   80,   80,   80,   80,  188,   80,   80,
       80,   80,  188,  168,   80,   80,  188,   80,  169,   80,
       80,  188,   80,   80,   80,   80,   80,   80,   80,   80,
      177,   80,  188,   80,   80,   80,   80,  172,  177,  176,
       80,   80,   80,   80,   80,  178,  178,  188,   80,   80,
       80,   80,  188,  178,  178,  182,  182,   80,  182,  188,
      182,  183,  183,  188,  183,  188,  183,  188,  188,  188,

      188,  188,  182,  178,  178,  188,  188,  184,  183,  183,
      183,  188,  183,  188,  183,  185,  188,  183,  183,  188,
      183,  188,  183,  188,  183,  183,  183,  183,  188,  183,
      188,  188,  188,  185,  183,  188,  182,  188,  188,  188,
      184,  183,  183,  188,  188,  188,  183,  183,  185,  183,
      188,  183,  188,  188,  188,  188,  188,  188,  188,  188,
      183,  188,  188,  183,  188,  188,  188,  188,  183,  188,
      185,  188,  188,  188,  188,  183,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  183,   51,   51,

      188,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,  188,  188,  188,   69,   80,  188,  188,
      188,   80,   80,   80,   80,   82,  188,  188,  188,   82,
      188,   82,   83,  188,  188,   83,   83,   83,  188,   83,
      107,  107,  107,  107,  107,  188,  107,  188,  107,  107,
      188,  188,  188,  107,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  111,
      111,  188,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  174,
      188,  174,  188,  188,  188,  188,  188,  174,  181,  188,
      188,  188,  188,  188,  181,  188,  181,  186,  186,  186,
      188,  186,  186,  188,  188,  188,  188,  186,  188,  188,
      186,  187,  187,  187,  188,  187,  188,  188,  188,  188,
      188,  187,  188,  188,  187,    3,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188
    } ;

static yyconst short int yy_chk[812] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,   12,   10,   17,   19,
       20,   20,  171,   22,   21,   22,   22,   19,   17,   21,
       23,   12,   23,   23,   26,   21,   26,   26,   28,   28,
       29,   34,  163,   29,   34,   10,   35,  162,   36,   35,
       10,   36,   40,   37,  151,   40,   37,   35,   34,  150,

       38,   45,   45,   38,   36,   29,   34,   37,   40,   45,
      131,   35,   39,   36,   38,   39,   38,   40,   37,   42,
       41,   39,   42,   41,  130,   38,   43,   39,   41,   43,
       42,   42,   44,   47,   52,   44,   47,   39,   42,   83,
       52,   43,   83,   52,   42,   41,  105,   53,   44,   53,
       52,   43,   65,   65,   66,   66,  104,   44,   70,   70,
       71,   47,   71,   71,   72,   66,   72,   72,   80,   80,
       85,   86,  102,   85,   85,  102,   80,   53,   86,   86,
       52,   85,   53,   87,   87,  103,   86,   88,   88,   79,
      190,   87,   87,  190,   88,   88,   89,   89,   75,   90,

       90,   89,   91,   91,   89,   90,   59,   90,   92,   92,
       91,   93,   93,   94,   94,   93,   92,   95,   95,   93,
       55,   94,   95,   97,   97,   95,   96,   96,   96,   97,
      170,   97,  170,   98,   98,   96,   99,   99,   54,   96,
       98,   98,  100,  100,   99,  106,  108,  108,  106,   51,
      100,  109,  109,  114,  106,  106,  175,  108,  110,  110,
      114,  114,  109,   32,  115,  115,  133,  133,  114,  110,
      115,  179,  115,  116,  110,  175,  118,  133,  117,  116,
      116,  117,  117,  118,  118,  106,  173,  116,  173,  117,
      179,  118,  119,  119,  120,  120,  121,  121,  121,   27,

      119,   24,  120,  122,  122,  121,   16,  123,  123,   11,
        9,  122,  122,  123,    8,  123,  124,  124,  125,    3,
      124,  125,  125,    0,  124,  126,  126,  127,  127,  125,
        0,    0,  128,  126,  126,  127,  128,  128,  129,  129,
        0,  129,  134,  134,  128,    0,  129,  136,  136,  136,
      137,  137,    0,  134,    0,  136,  138,  138,  137,  138,
      139,  139,  140,  140,  138,  141,  141,    0,  139,  180,
      140,  142,  142,  141,  143,  143,    0,  142,    0,  142,
      144,    0,  143,  144,  144,  145,  145,    0,  180,  146,
      145,  144,    0,  145,  146,  146,  147,  147,  147,  148,

      148,    0,  146,  152,  152,  147,  149,  148,    0,  149,
      149,  152,  153,  154,  154,  153,  153,  149,  155,  155,
        0,  154,  155,  153,  156,  156,  155,    0,  158,  157,
      158,  158,  156,  157,  157,  159,  159,    0,  158,  161,
      161,  157,    0,  159,  160,  160,    0,  161,  160,  164,
      164,    0,  160,  165,  165,  166,  166,  164,  167,  167,
      174,  165,  174,  166,  168,  168,  167,  169,  177,  172,
      169,  169,  168,  172,  172,  174,  174,    0,  169,  176,
      176,  172,    0,  177,  177,  178,  178,  176,  178,    0,
      178,  181,  181,    0,  181,    0,  181,    0,    0,    0,

        0,    0,  178,  178,  178,    0,    0,  181,  181,  184,
      184,    0,  184,    0,  184,  181,    0,  185,  185,    0,
      185,    0,  185,    0,  186,  186,  184,  186,    0,  186,
        0,    0,    0,  184,  185,    0,  178,    0,    0,    0,
      186,  186,  181,    0,    0,    0,  187,  187,  186,  187,
        0,  187,    0,    0,    0,    0,    0,    0,    0,    0,
      184,    0,    0,  187,    0,    0,    0,    0,  185,    0,
      187,    0,    0,    0,    0,  186,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  187,  189,  189,

        0,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,    0,    0,    0,  191,  192,    0,    0,
        0,  192,  192,  192,  192,  193,    0,    0,    0,  193,
        0,  193,  194,    0,    0,  194,  194,  194,    0,  194,
      195,  195,  195,  195,  195,    0,  195,    0,  195,  195,
        0,    0,    0,  195,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  197,
      197,    0,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  198,  198,  198,  198,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  199,
        0,  199,    0,    0,    0,    0,    0,  199,  200,    0,
        0,    0,    0,    0,  200,    0,  200,  201,  201,  201,
        0,  201,  201,    0,    0,    0,    0,  201,    0,    0,
      201,  202,  202,  202,    0,  202,    0,    0,    0,    0,
        0,  202,    0,    0,  202,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,

      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
	#include <stdio.h>
	#include <string.h>
	#include "parser.tab.h"


	
	int nestedno = 0;
	int top = 0;
	int errno = 1;
	int bound1stack[100];
	int bound2stack[100];
	struct symboltable
	{
		char name[100];
		char class[100];
		char type[100];
		char value[100];
		int lineno;
		int length;
		int nestedno;
		int boundary1;
		int boundary2;
	}ST[1001];

	struct constanttable
	{
		char name[100];
		char type[100];
		int length;
	}CT[1001];

	int hash(char *str)
	{
		int value = 0;
		for(int i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 1001;
			while(value < 0)
				value = value + 1001;
		}
		return value;
	}

	int lookupST(char *str)
	{
		int value = hash(str);
		if(ST[value].length == 0)
		{
			return 0;
		}
		else if(strcmp(ST[value].name,str)==0)
		{
			return 1;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}

	int lookupCT(char *str)
	{
		int value = hash(str);
		if(CT[value].length == 0)
			return 0;
		else if(strcmp(CT[value].name,str)==0)
			return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(CT[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}
	void insertSTtype(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				strcpy(ST[i].type,str2);
			}
		}
    }

	void insertSTvalue(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				strcpy(ST[i].value,str2);
			}
		}
	}

	void insertSTline(char *str1, int line)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				ST[i].lineno = line;
			}
		}
	}

	void insertSTnested(char *str1, int nested) {
		for (int i = 0; i<1001; i++) {
			if (strcmp(ST[i].name, str1)==0) {
				ST[i].nestedno = nestedno;
			}
		}
	}

	void insertST(char *str1, char *str2)
	{
		if(lookupST(str1))
		{
			return;
		}
		else
		{
			int value = hash(str1);
			if(ST[value].length == 0)
			{
				strcpy(ST[value].name,str1);
				strcpy(ST[value].class,str2);
				ST[value].length = strlen(str1);
				insertSTline(str1,yylineno);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,str1);
			strcpy(ST[pos].class,str2);
			ST[pos].length = strlen(str1);
		}
	}

	void insertCT(char *str1, char *str2)
	{
		if(lookupCT(str1))
			return;
		else
		{
			int value = hash(str1);
			if(CT[value].length == 0)
			{
				strcpy(CT[value].name,str1);
				strcpy(CT[value].type,str2);
				CT[value].length = strlen(str1);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(CT[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(CT[pos].name,str1);
			strcpy(CT[pos].type,str2);
			CT[pos].length = strlen(str1);
		}
	}

	void printST()
	{
		for(int i=0;i<186;i++) {
			printf("=");
			}
		printf("\n%20s | %25s | %20s | %20s | %20s | %20s | %20s | %20s\n","SYMBOL", "CLASS", "TYPE","VALUE", "LINE NO", "NESTED LEVEL", "UPPER BOUND", "LOWER BOUND");
		for(int i=0;i<186;i++) {
			printf("=");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].length == 0)
			{
				continue;
			}
			if(strcmp(ST[i].class, "Identifier")==0 || strcmp(ST[i].class, "Array Identifier")==0) {
				for(int j = 0; j<top; j++) {
					if (bound1stack[j] <= ST[i].lineno && ST[i].lineno <= bound2stack[j]) {
						ST[i].boundary1 = bound1stack[j];
						ST[i].boundary2 = bound2stack[j]-1;
					}
					else {
						break;
					}
				}
			}
			if((strcmp(ST[i].class, "Identifier")==0 || strcmp(ST[i].class, "Array Identifier")==0)&&(strcmp(ST[i].name, "main")!=0) && (strcmp(ST[i].name, "printf")!=0) && (strcmp(ST[i].name, "scanf") != 0) ) {
				printf("%20s | %25s | %20s | %20s | %20d | %20d | %20d | %20d\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].nestedno, ST[i].boundary1, ST[i].boundary2);
			} else {
				printf("%20s | %25s | %20s | %20s | %20d | %20d | %20s | %20s\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].nestedno, "", "");
			}
		}
    }


	void printCT()
	{
	for(int i=0;i<186;i++) {
		printf("=");
	}
		printf("\n%20s | %25s\n","NAME", "TYPE");
		for(int i=0;i<186;i++) {
			printf("=");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(CT[i].length == 0)
				continue;

			printf("%20s | %25s\n",CT[i].name, CT[i].type);
		}
	}
	char curid[20];
	char curtype[20];
	char curval[20];

#line 902 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 260 "scanner.l"

#line 1055 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 189 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 756 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 261 "scanner.l"
{errno++;}
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 262 "scanner.l"
{ }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 263 "scanner.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 264 "scanner.l"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 265 "scanner.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 266 "scanner.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 267 "scanner.l"
{ return(';'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 268 "scanner.l"
{ return(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 269 "scanner.l"
{ bound1stack[nestedno++] = yylineno; top++; return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 270 "scanner.l"
{ bound2stack[--nestedno] = yylineno; return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 271 "scanner.l"
{ return('('); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 272 "scanner.l"
{ return(')'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 273 "scanner.l"
{ return('['); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 274 "scanner.l"
{ return(']'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 275 "scanner.l"
{ return(':'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 276 "scanner.l"
{ return('.'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 278 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return CHAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 279 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 280 "scanner.l"
{ insertSTline(yytext, yylineno); insertST(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 281 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return FLOAT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 282 "scanner.l"
{ insertST(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 283 "scanner.l"
{ insertST(yytext, "Keyword"); return DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 284 "scanner.l"
{ insertST(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 285 "scanner.l"
{ insertST(yytext, "Keyword"); return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 286 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return INT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 287 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return LONG;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 288 "scanner.l"
{ insertST(yytext, "Keyword");  return RETURN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 289 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return SHORT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 290 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return SIGNED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 291 "scanner.l"
{ insertST(yytext, "Keyword");  return SIZEOF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 292 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 293 "scanner.l"
{ insertST(yytext, "Keyword");  return UNSIGNED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 294 "scanner.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 295 "scanner.l"
{ insertST(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 298 "scanner.l"
{ return increment_operator; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 299 "scanner.l"
{ return decrement_operator; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 300 "scanner.l"
{ return leftshift_operator; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 301 "scanner.l"
{ return rightshift_operator; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 302 "scanner.l"
{ return lessthan_assignment_operator; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 303 "scanner.l"
{ return lessthan_operator; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 304 "scanner.l"
{ return greaterthan_assignment_operator; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 305 "scanner.l"
{ return greaterthan_operator; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 306 "scanner.l"
{ return equality_operator; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 307 "scanner.l"
{ return inequality_operator; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 308 "scanner.l"
{ return AND_operator; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 309 "scanner.l"
{ return OR_operator; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 310 "scanner.l"
{ return caret_operator; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 311 "scanner.l"
{ return multiplication_assignment_operator; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 312 "scanner.l"
{ return division_assignment_operator; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 313 "scanner.l"
{ return modulo_assignment_operator; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 314 "scanner.l"
{ return addition_assignment_operator; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 315 "scanner.l"
{ return subtraction_assignment_operator; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 316 "scanner.l"
{ return leftshift_assignment_operator; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 317 "scanner.l"
{ return rightshift_assignment_operator; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 318 "scanner.l"
{ return AND_assignment_operator; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 319 "scanner.l"
{ return XOR_assignment_operator; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 320 "scanner.l"
{ return OR_assignment_operator; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 321 "scanner.l"
{ return amp_operator; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 322 "scanner.l"
{ return exclamation_operator; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 323 "scanner.l"
{ return tilde_operator; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 324 "scanner.l"
{ return subtract_operator; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 325 "scanner.l"
{ return add_operator; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 326 "scanner.l"
{ return multiplication_operator; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 327 "scanner.l"
{ return division_operator; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 328 "scanner.l"
{ return modulo_operator; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 329 "scanner.l"
{ return pipe_operator; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 330 "scanner.l"
{ return assignment_operator;}
	YY_BREAK
case 68:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 332 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext,"String Constant"); return string_constant;}
	YY_BREAK
case 69:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 333 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 70:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 334 "scanner.l"
{strcpy(curid,yytext); insertST(yytext, "Array Identifier");  return identifier;}
	YY_BREAK
case 71:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 335 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext, "Number Constant"); return integer_constant;}
	YY_BREAK
case 72:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 336 "scanner.l"
{strcpy(curval,yytext); insertCT(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 337 "scanner.l"
{strcpy(curid,yytext);insertST(yytext,"Identifier");  return identifier;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 339 "scanner.l"
{
		if(yytext[0]=='#')
		{
			printf("Error in Pre-Processor directive at line no. %d\n",errno);
		}
		else if(yytext[0]=='/')
		{
			printf("ERR_UNMATCHED_COMMENT at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='"')
		{
			printf("ERR_INCOMPLETE_STRING at line no. %d\n",yylineno);
		}
		else
		{
			printf("ERROR at line no. %d\n",yylineno);
		}
		printf("%s\n", yytext);
		return 0;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 360 "scanner.l"
ECHO;
	YY_BREAK
#line 1561 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 189 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 189 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 188);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 360 "scanner.l"
